fixes offset limit duplication
sebastienros/yessql pull request #490
Opened 2023-07-24 23:28 UTC by brunoAltinet

this fixes when different skip/take is used on a same query

Fixes #433 

often a case when doing batching

2023-07-25 17:25 UTC, hishamco requested changes

2023-07-25 17:25 UTC, hishamco commented on src/YesSql.Provider.SqlServer/SqlServerDialect.cs
> +            sqlBuilder.ClearTrail();
```suggestion
            sqlBuilder.ClearTrail();

```

2023-07-25 17:25 UTC, hishamco commented on test/YesSql.Tests/CoreTests.cs
> +                Assert.Equal(5, (await query.Skip(10).Take(5).ListAsync()).Count());
Can we create a new test for this?

2023-10-11 19:03 UTC, merged

2023-10-11 21:07 UTC, sebastienros commented
I reverted it since it was failing the PostgreSQL tests.